name: Desafio de Variaveis e Escopos

on:
  workflow_dispatch:

env:
  APP_NAME: "Sistema de Gerenciamento"

jobs:
  build_app:
    runs-on: ubuntu-latest
    env:
      BUILD_VERSION: "v1.2.0"
    steps:
      - name: Variaveis de Escopo
        run: |
          echo "App: $APP_NAME"
          echo "Versao: $BUILD_VERSION"
      
      - name: Variavel Dinamica
        run: echo "BUILD_HASH=$RANDOM" >> $GITHUB_ENV

      - name: Log do Hash
        run: echo "O hash gerado foi $BUILD_HASH"

  deploy_app:
    needs: build_app
    runs-on: ubuntu-latest
    steps:
      - name: Segredos e Vars
        env:
          URL: ${{ vars.URL_AMBIENTE }}
          TOKEN: ${{ secrets.API_TOKEN_PROD }}
        run: |
          echo "URL: $URL"
          echo "Token: $TOKEN"