name: Desafio Final
on:
  workflow_dispatch:
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Verificando Variaveis
        env:
          URL: ${{ vars.URL_AMBIENTE }}
          TOKEN: ${{ secrets.API_TOKEN_PROD }}
        run: |
          echo "App: ${{ github.repository }}"
          echo "URL: $URL"
          echo "Token: $TOKEN"